[package]
name = "ld-nom"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0", "target-x86"], default-features = false }